theme: jekyll-theme-cayman
title: Talawah Solutions
description: Cloud Computing Consulting

upwork_url: 'https://www.upwork.com/agencies/~01fad6222c34cc5fea'
linkedin_url: 'https://www.linkedin.com/company/talawah/'
blog_url: 'https://medium.com/@talawahtech'
github_url: 'https://github.com/talawahtech'
